
'use server';
/**
 * @fileOverview A Genkit flow for summarizing the content of a webpage.
 *
 * - summarizeWebpage - A function that handles the webpage summarization.
 * - SummarizeWebpageInput - The input type for the summarizeWebpage function.
 * - SummarizeWebpageOutput - The return type for the summarizeWebpage function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
// fetchUrlContentTool is not directly used if we bypass the prompt, but kept for potential future use or direct tool calls.
// import { fetchUrlContentTool } from '@/ai/tools/fetch-url-content-tool';

const SummarizeWebpageInputSchema = z.object({
  url: z.string().url().describe('The URL of the webpage to summarize.'),
});
export type SummarizeWebpageInput = z.infer<typeof SummarizeWebpageInputSchema>;

const SummarizeWebpageOutputSchema = z.object({
  summary: z.string().describe('The summarized content of the webpage.'),
  originalUrl: z.string().url().describe('The original URL that was summarized.'),
  error: z.string().optional().describe('An error message if summarization failed or content could not be fetched.'),
});
export type SummarizeWebpageOutput = z.infer<typeof SummarizeWebpageOutputSchema>;

export async function summarizeWebpage(input: SummarizeWebpageInput): Promise<SummarizeWebpageOutput> {
  return summarizeWebpageFlow(input);
}

// Original prompt definition commented out as we are simulating the flow's output directly.
// const summarizePrompt = ai.definePrompt({
//   name: 'summarizeWebpagePrompt',
//   input: { schema: SummarizeWebpageInputSchema },
//   output: { schema: SummarizeWebpageOutputSchema },
//   tools: [fetchUrlContentTool],
//   prompt: `You are a helpful AI assistant that summarizes webpages.
//   1. Use the 'fetchUrlContentTool' to get the text content of the webpage at the given URL: {{{url}}}.
//   2. If the tool returns an error or empty content, set the 'error' field in your output and provide a brief explanation. Do not attempt to summarize and ensure the 'summary' field is an empty string.
//   3. If you receive content, provide a concise summary of the text.
//   4. Ensure your output includes the original URL and the summary.
//   `,
// });

const summarizeWebpageFlow = ai.defineFlow(
  {
    name: 'summarizeWebpageFlow',
    inputSchema: SummarizeWebpageInputSchema,
    outputSchema: SummarizeWebpageOutputSchema,
  },
  async (input) => {
    // Simulate backend call to SuperAGI/CrewAI or LLM for summarization
    console.log(`[SIMULATE] summarizeWebpageFlow called with URL: "${input.url}"`);

    if (input.url.includes("error.com")) {
        return {
            summary: '',
            originalUrl: input.url,
            error: 'Simulated error: Failed to fetch or summarize content from error.com.',
        };
    }
    if (!input.url || !input.url.startsWith('http')) {
        return {
            summary: '',
            originalUrl: input.url || 'invalid_url',
            error: 'Invalid URL provided for summarization.',
        };
    }

    // Simulate a successful summarization response
    return {
      summary: `This is a simulated summary for the webpage at ${input.url}. The actual summary would be generated by the SuperAGI/CrewAI backend. It would typically involve fetching the content and then processing it with an LLM. For example, it might highlight key points, extract entities, and provide an overall sentiment if configured to do so.`,
      originalUrl: input.url,
    };

    // Original Genkit prompt call is commented out.
    // const llmResponse = await summarizePrompt(input);
    // const output = llmResponse.output;

    // if (!output) {
    //   let errorMessage = "Failed to generate summary. The LLM did not produce valid output.";
    //   if (llmResponse.candidates && llmResponse.candidates.length > 0) {
    //     const firstCandidate = llmResponse.candidates[0];
    //     if (firstCandidate.finishReason !== 'STOP' && firstCandidate.finishMessage) {
    //         errorMessage = `LLM generation incomplete: ${firstCandidate.finishMessage} (Reason: ${firstCandidate.finishReason})`;
    //     } else if (firstCandidate.blocked && firstCandidate.blockedMessage) {
    //          errorMessage = `LLM response blocked by safety settings or other policy: ${firstCandidate.blockedMessage}`;
    //     }
    //   }
    //   return {
    //     summary: '',
    //     originalUrl: input.url,
    //     error: errorMessage,
    //   };
    // }
    
    // if (output.error) {
    //     return {
    //         summary: '', 
    //         originalUrl: input.url,
    //         error: output.error,
    //     };
    // }

    // if (!output.summary && !output.error) {
    //     return {
    //         summary: '',
    //         originalUrl: input.url,
    //         error: 'The webpage might have no summarizable content, or the AI chose not to summarize.',
    //     };
    // }
    
    // return output; 
  }
);
