// src/components/ai/ai-flow-generator-form.tsx
'use client';

import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { Send, Loader2 } from 'lucide-react';
import type { AiGeneratedFlowData, WorkflowNodeData } from '@/app/page';
// Updated import to use the new task function
import { generateDataCleanupTask, type GenerateDataCleanupOutput, type GenerateDataCleanupInput } from '@/tasks/generate-data-cleanup-task';
import { generateNodeId } from '@/lib/utils';


interface AiFlowGeneratorFormProps {
  onFlowGenerated: (data: AiGeneratedFlowData) => void;
}

export function AiFlowGeneratorForm({ onFlowGenerated }: AiFlowGeneratorFormProps) {
  const [userInput, setUserInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!userInput.trim()) {
      toast({
        title: "Input Required",
        description: "Please describe the flow you want to generate.",
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);
    console.log(`[AI_FLOW_FORM] Calling task 'generateDataCleanupTask' for input: "${userInput.substring(0, 50)}..."`);
    
    try {
      // Call the new task function
      const taskInput: GenerateDataCleanupInput = { userInput };
      const taskOutput: GenerateDataCleanupOutput = await generateDataCleanupTask(taskInput);

      if (taskOutput.error) {
        throw new Error(taskOutput.error);
      }

      const nodes: WorkflowNodeData[] = taskOutput.promptSequence.map((promptText, index) => {
        let stepTitle = promptText.substring(0, 30);
        if (stepTitle.length === 30 && promptText.length > 30) stepTitle += "...";
        
        const nodeTitle = `${taskOutput.workflowDescription} - ${stepTitle || `Step ${index + 1}`}`;
        
        return {
          id: generateNodeId('ai', taskOutput.workflowDescription, index),
          title: nodeTitle,
          description: `AI Generated Step: ${promptText}`,
          type: 'prompt', 
          status: 'queued',
          config: {
            promptText: promptText,
          },
          position: { x: 50 + (index * 20), y: 100 + index * 100 }, 
        };
      });

      const generatedData: AiGeneratedFlowData = {
        message: `Flow "${taskOutput.workflowDescription}" generated successfully with ${nodes.length} steps from AI (simulated task).`,
        workflowName: taskOutput.workflowDescription,
        nodes: nodes,
        error: false,
        userInput: userInput,
      };
      
      toast({
        title: "Flow Generated by AI (Simulated Task)",
        description: generatedData.message,
      });
      onFlowGenerated(generatedData);

    } catch (e: any) {
      console.error("[AI_FLOW_FORM] Error generating flow with task:", e);
      const errorMessage = e.message || "AI (simulated task) failed to generate a flow from the provided input.";
      
      const generatedData: AiGeneratedFlowData = {
        message: errorMessage,
        error: true,
        userInput: userInput,
        nodes: [], 
      };

      toast({
        title: "AI Flow Generation Failed (Simulated Task)",
        description: errorMessage,
        variant: "destructive",
      });
      onFlowGenerated(generatedData);
    } finally {
      setIsLoading(false);
      setUserInput(''); 
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex items-end gap-2">
      <div className="flex-grow">
        <Label htmlFor="userInput" className="sr-only">
          Describe the flow to generate
        </Label>
        <Input
          id="userInput"
          name="userInput"
          type="text"
          placeholder="Describe an agent workflow to generate with AI..."
          className="bg-input/80 backdrop-blur-sm border-border/70 focus:ring-ring"
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          disabled={isLoading}
        />
      </div>
      <Button type="submit" aria-disabled={isLoading} disabled={isLoading} size="sm">
        {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" /> }
        {isLoading ? 'Generating...' : 'Generate Flow'}
      </Button>
    </form>
  );
}
