
// src/components/ai/ai-flow-generator-form.tsx
'use client';

import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { Send, Loader2 } from 'lucide-react';
import type { AiGeneratedFlowData, WorkflowNodeData } from '@/app/page'; 
import { generateNodeId } from '@/lib/utils';


interface AiFlowGeneratorFormProps {
  onFlowGenerated: (data: AiGeneratedFlowData) => void;
}

export function AiFlowGeneratorForm({ onFlowGenerated }: AiFlowGeneratorFormProps) {
  const [userInput, setUserInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!userInput.trim()) {
      toast({
        title: "Input Required",
        description: "Please describe the flow you want to generate.",
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);
    let accumulatedResponse = "";
    let accumulatedLogs = "";

    try {
      console.log(`[AI_FLOW_FORM] Calling API /api/loom/start for input: "${userInput.substring(0, 50)}..."`);
      const response = await fetch('/api/loom/start', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt: userInput }), // Sending as a general prompt
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: "Failed to parse error response from API." }));
        throw new Error(errorData.error || `API request failed with status ${response.status}`);
      }

      if (!response.body) {
        throw new Error("Response body is empty.");
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let done = false;

      while (!done) {
        const { value, done: readerDone } = await reader.read();
        done = readerDone;
        if (value) {
          const chunk = decoder.decode(value, { stream: true });
          accumulatedResponse += chunk;
        }
      }
      
      // Parse the stream: separate logs from final output
      const logMarker = "[LOG]";
      const outputStartMarker = "[STREAMING_OUTPUT_START]";
      const errorMarker = "[ERROR]";
      let finalOutput = "";
      const logLines: string[] = [];
      let outputStarted = false;
      let apiErrorFound = "";

      const lines = accumulatedResponse.split('\n');
      for (const line of lines) {
        if (line.startsWith(errorMarker)) {
          apiErrorFound = line.substring(errorMarker.length).trim();
          break; 
        }
        if (line.startsWith(outputStartMarker)) {
          outputStarted = true;
          const contentAfterMarker = line.substring(outputStartMarker.length);
          if(contentAfterMarker.trim()) finalOutput += contentAfterMarker + '\n'; // Add content on the same line
          continue; 
        }
        if (line.startsWith(logMarker) && !outputStarted) {
          logLines.push(line.substring(logMarker.length).trim());
        } else if (outputStarted) {
          finalOutput += line + '\n';
        }
      }
      accumulatedLogs = logLines.join('\n');
      finalOutput = finalOutput.trim();
      
      console.log("[AI_FLOW_FORM] API Response Logs:\n", accumulatedLogs);
      console.log("[AI_FLOW_FORM] API Final Output:\n", finalOutput);

      if (apiErrorFound) {
        throw new Error(`API returned an error: ${apiErrorFound}`);
      }

      if (!finalOutput && !apiErrorFound) { // If no error marker, but also no output
         throw new Error("No actionable output received from the AI flow generation API. Logs: " + accumulatedLogs.substring(0, 200) + "...");
      }

      const workflowName = `Flow for: ${userInput.substring(0, 30)}${userInput.length > 30 ? '...' : ''}`;
      const nodeTitle = `AI Generated Step for: ${userInput.substring(0, 20)}${userInput.length > 20 ? '...' : ''}`;

      const nodes: WorkflowNodeData[] = [{
        id: generateNodeId('ai', workflowName, 0),
        title: nodeTitle,
        description: `AI Generated Step: ${finalOutput.substring(0, 100)}${finalOutput.length > 100 ? "..." : ""}`,
        type: 'prompt', 
        status: 'queued',
        config: {
          promptText: finalOutput,
        },
        position: { x: 50, y: 100 }, 
      }];

      const generatedData: AiGeneratedFlowData = {
        message: `Flow "${workflowName}" generated successfully by backend AI. Logs: ${accumulatedLogs.substring(0,100)}...`,
        workflowName: workflowName,
        nodes: nodes,
        error: false,
        userInput: userInput,
      };
      
      toast({
        title: "Flow Generated by Backend AI",
        description: generatedData.message,
      });
      onFlowGenerated(generatedData);

    } catch (e: any) {
      console.error("[AI_FLOW_FORM] Error generating flow with API:", e);
      const errorMessage = e.message || "AI backend failed to generate a flow from the provided input.";
      
      const generatedData: AiGeneratedFlowData = {
        message: errorMessage,
        error: true,
        userInput: userInput,
        nodes: [], 
      };

      toast({
        title: "AI Flow Generation Failed (Backend API)",
        description: errorMessage,
        variant: "destructive",
      });
      onFlowGenerated(generatedData);
    } finally {
      setIsLoading(false);
      setUserInput(''); 
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex items-end gap-2">
      <div className="flex-grow">
        <Label htmlFor="userInput" className="sr-only">
          Describe the flow to generate
        </Label>
        <Input
          id="userInput"
          name="userInput"
          type="text"
          placeholder="Describe an agent workflow to generate with AI..."
          className="bg-input/80 backdrop-blur-sm border-border/70 focus:ring-ring"
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          disabled={isLoading}
        />
      </div>
      <Button type="submit" aria-disabled={isLoading} disabled={isLoading} size="sm">
        {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" /> }
        {isLoading ? 'Generating...' : 'Generate Flow'}
      </Button>
    </form>
  );
}
