// src/components/ai/webpage-summarizer-form.tsx
'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Loader2, Link, Search, FileText, AlertCircle } from 'lucide-react';
import type { ConsoleMessage } from '@/components/panels/console-panel';
import type { TimelineEvent } from '@/components/panels/timeline-panel';
import type { BackendSummarizeOutput } from '@/app/page'; // Using page types

interface WebpageSummarizerFormProps {
  addConsoleMessage: (type: ConsoleMessage['type'], text: string) => void;
  addTimelineEvent: (event: Omit<TimelineEvent, 'id' | 'timestamp'>) => void;
}

export function WebpageSummarizerForm({ addConsoleMessage, addTimelineEvent }: WebpageSummarizerFormProps) {
  const [url, setUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<BackendSummarizeOutput | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!url) {
      setError('Please enter a URL.');
      addConsoleMessage('warn', 'Webpage Summarizer: URL input is empty.');
      return;
    }

    setIsLoading(true);
    setResult(null); 
    setError(null);   

    addConsoleMessage('log', `Webpage Summarizer: Simulating summarization via SuperAGI backend for URL: ${url}`);
    addTimelineEvent({
      type: 'info', 
      message: `Agent 'Webpage Summarizer' (via SuperAGI simulation) started for URL: ${url.substring(0, 50)}...`,
    });

    // Simulate API call to FastAPI backend
    await new Promise(resolve => setTimeout(resolve, 1500 + Math.random() * 1000));

    let output: BackendSummarizeOutput;

    // Simulate backend response
    if (Math.random() > 0.2) { // Simulate success
      output = {
        summary: `This is a simulated summary for the webpage at ${url}. The actual summary would be generated by the SuperAGI backend. It might include key points, entities, and overall sentiment.`,
        originalUrl: url,
      };
      setResult(output);
      setError(null);
      addConsoleMessage('info', `Webpage Summarizer (SuperAGI simulation): Successfully summarized ${url}.`);
      addTimelineEvent({
        type: 'workflow_completed',
        message: `Agent 'Webpage Summarizer' (SuperAGI simulation) completed for ${url.substring(0,50)}...`,
      });
    } else { // Simulate error
      const errorMessage = "Simulated API Error: The SuperAGI backend could not summarize the webpage. The URL might be invalid or the content inaccessible.";
      output = {
        error: errorMessage,
        originalUrl: url,
      };
      setResult(output);
      setError(errorMessage);
      addConsoleMessage('error', `Webpage Summarizer (SuperAGI simulation): Failed - ${errorMessage}`);
      addTimelineEvent({
        type: 'workflow_failed', 
        message: `Agent 'Webpage Summarizer' (SuperAGI simulation) failed: ${errorMessage.substring(0,100)}`,
      });
    }
    setIsLoading(false);
  };

  return (
    <div className="space-y-3">
      <form onSubmit={handleSubmit} className="space-y-3">
        <div>
          <Label htmlFor="webpageUrl" className="text-xs flex items-center gap-1.5 mb-1">
            <Link className="h-3.5 w-3.5 text-primary/80" /> Webpage URL
          </Label>
          <Input
            id="webpageUrl"
            name="webpageUrl"
            type="url"
            placeholder="https://example.com/article"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            className="bg-input/70 backdrop-blur-sm border-border/70 focus:ring-ring"
            disabled={isLoading}
          />
        </div>
        <Button type="submit" disabled={isLoading || !url} className="w-full" size="sm">
          {isLoading ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Search className="mr-2 h-4 w-4" />
          )}
          {isLoading ? 'Summarizing (Sim SuperAGI)...' : 'Summarize (Simulate SuperAGI)'}
        </Button>
      </form>

      {error && (!result || !result.summary) && ( // Show error if error exists and no summary
        <Alert variant="destructive">
           <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error (Simulated SuperAGI)</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {result && result.summary && (
        <div className="space-y-2 pt-2">
          <h4 className="text-sm font-medium flex items-center gap-1.5">
            <FileText className="h-4 w-4 text-primary/90" />
            Summary (from SuperAGI Sim) for: <a href={result.originalUrl} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline truncate max-w-[150px] sm:max-w-[200px] md:max-w-[220px] inline-block" title={result.originalUrl}>{result.originalUrl}</a>
          </h4>
          <Textarea
            value={result.summary}
            readOnly
            rows={6}
            className="bg-input/50 backdrop-blur-sm border-input/50 focus:ring-ring text-xs"
          />
        </div>
      )}
       {result && !result.summary && result.error && ( // Handles case where API returns an error object without a summary
        <Alert variant="destructive" className="mt-2">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Summarization Error (Simulated SuperAGI)</AlertTitle>
          <AlertDescription>{result.error}</AlertDescription>
        </Alert>
      )}
      
    </div>
  );
}
